### ISSUE TITLE
How does anchor, anchorX, anchorY works in latest Playground?

### ISSUE THREAD

**Issue by kotori2** [KLab/PlaygroundOSS#76]
Hi, I'm kinda confused about how does fullscreen stuffs works in Playground. Could you please give me a hint?

**Comment by Romain-Piquois** [comment]
Hello,

Such properties like anchor, anchorX, anchorY (and some others) have been introduced quite later in the development stage of our game due to device evolution. Therefore the formatting system to support such feature was not reflected in the open source version later on. 

So, what kind of data are you looking at... :-) ?

**Comment by kotori2** [comment]
I'm trying to implement APIs that was in latest not open source version Playground, which was used in SIF now. It will be great if you can disclose some of the latest full screen support documents. <3

**Comment by Romain-Piquois** [comment]
For obvious reason, I'm sorry but I can't disclose anything related to SIF (KLab's internal property) so I am closing the subject.
